# Generated by Django 3.0.2 on 2020-01-22 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20200122_2317'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='shippingPostCode',
            new_name='shippingPostcode',
        ),
    ]
